import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import MainLayout from '../layout/MainLayout'
import Intro from '../components/utils/Intro'

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Magna Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
          <Intro />
        </div>
    </MainLayout>
  )
}
